services:
    # no comment after code // here
    SlevomatCodingStandard\Sniffs\Commenting\DisallowCommentAfterCodeSniff: null

    # check for forgotten "git merge" conflicts
    PHP_CodeSniffer\Standards\Generic\Sniffs\VersionControl\GitMergeConflictSniff: null

    # remove empty inline comments
    SlevomatCodingStandard\Sniffs\Commenting\EmptyCommentSniff:
