services:
    # $this->assertEquals()    =>    $this->assertSame()
    PhpCsFixer\Fixer\PhpUnit\PhpUnitStrictFixer: null

    # test<>()
    PhpCsFixer\Fixer\PhpUnit\PhpUnitTestAnnotationFixer: null

    # public setUp()   =>   protected setUp()
    PhpCsFixer\Fixer\PhpUnit\PhpUnitSetUpTearDownVisibilityFixer: null
