services:
    SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff: null
    SlevomatCodingStandard\Sniffs\Functions\UnusedInheritedVariablePassedToClosureSniff: null
    SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff: null
    SlevomatCodingStandard\Sniffs\Variables\UnusedVariableSniff: null

parameters:
    skip:
        SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff.UnusedParameter: null
