services:
    # All elements should have visibility
    PhpCsFixer\Fixer\ClassNotation\VisibilityRequiredFixer:
        elements: [const, property, method]

    # Turn list() into []
    PhpCsFixer\Fixer\ListNotation\ListSyntaxFixer:
        syntax: short

    # Nullable Typehints
    SlevomatCodingStandard\Sniffs\TypeHints\NullableTypeForNullDefaultValueSniff: null
    PhpCsFixer\Fixer\Whitespace\CompactNullableTypehintFixer: null

    # Void Typehints
    PhpCsFixer\Fixer\FunctionNotation\VoidReturnFixer: null
