imports:
    - { resource: 'services/*' }
    - { resource: 'parameters/parameter_name_guard.yaml' }

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\EasyCodingStandard\:
        resource: '../src'
        exclude:
            - '../src/DependencyInjection/*'
            - '../src/HttpKernel/*'
            - '../src/Exception/*'
            - '../src/ValueObject/*'
            - '../src/Yaml/*'

    # Console
    Symfony\Component\Console\Terminal: null

    Symplify\PackageBuilder\Parameter\ParameterProvider: null
    Symplify\SmartFileSystem\FileSystemGuard: null
    Symplify\SmartFileSystem\Finder\FinderSanitizer: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\EasyCodingStandard\Console\Style\EasyCodingStandardStyle:
        factory: ['@Symplify\EasyCodingStandard\Console\Style\EasyCodingStandardStyleFactory', 'create']

    PhpCsFixer\WhitespacesFixerConfig:
        factory: ['@Symplify\EasyCodingStandard\FixerRunner\WhitespacesFixerConfigFactory', 'create']
